// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef CXX__CONFIG_HXX
#define CXX__CONFIG_HXX

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< char, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::auto_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
class PowerGridConfig_t;

#include <memory>    // ::std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

class PowerGridConfig_t: public ::xml_schema::type
{
  public:
  // Nx
  //
  typedef ::xml_schema::integer Nx_type;
  typedef ::xsd::cxx::tree::traits< Nx_type, char > Nx_traits;

  const Nx_type&
  Nx () const;

  Nx_type&
  Nx ();

  void
  Nx (const Nx_type& x);

  // Ny
  //
  typedef ::xml_schema::integer Ny_type;
  typedef ::xsd::cxx::tree::traits< Ny_type, char > Ny_traits;

  const Ny_type&
  Ny () const;

  Ny_type&
  Ny ();

  void
  Ny (const Ny_type& x);

  // Nz
  //
  typedef ::xml_schema::integer Nz_type;
  typedef ::xsd::cxx::tree::traits< Nz_type, char > Nz_traits;

  const Nz_type&
  Nz () const;

  Nz_type&
  Nz ();

  void
  Nz (const Nz_type& x);

  // Niter
  //
  typedef ::xml_schema::integer Niter_type;
  typedef ::xsd::cxx::tree::traits< Niter_type, char > Niter_traits;

  const Niter_type&
  Niter () const;

  Niter_type&
  Niter ();

  void
  Niter (const Niter_type& x);

  // Ntimeseg
  //
  typedef ::xml_schema::integer Ntimeseg_type;
  typedef ::xsd::cxx::tree::traits< Ntimeseg_type, char > Ntimeseg_traits;

  const Ntimeseg_type&
  Ntimeseg () const;

  Ntimeseg_type&
  Ntimeseg ();

  void
  Ntimeseg (const Ntimeseg_type& x);

  // Ncoils
  //
  typedef ::xml_schema::integer Ncoils_type;
  typedef ::xsd::cxx::tree::traits< Ncoils_type, char > Ncoils_traits;

  const Ncoils_type&
  Ncoils () const;

  Ncoils_type&
  Ncoils ();

  void
  Ncoils (const Ncoils_type& x);

  // Nshots
  //
  typedef ::xml_schema::integer Nshots_type;
  typedef ::xsd::cxx::tree::traits< Nshots_type, char > Nshots_traits;

  const Nshots_type&
  Nshots () const;

  Nshots_type&
  Nshots ();

  void
  Nshots (const Nshots_type& x);

  // Nphases
  //
  typedef ::xml_schema::integer Nphases_type;
  typedef ::xsd::cxx::tree::traits< Nphases_type, char > Nphases_traits;

  const Nphases_type&
  Nphases () const;

  Nphases_type&
  Nphases ();

  void
  Nphases (const Nphases_type& x);

  // Nimages
  //
  typedef ::xml_schema::integer Nimages_type;
  typedef ::xsd::cxx::tree::traits< Nimages_type, char > Nimages_traits;

  const Nimages_type&
  Nimages () const;

  Nimages_type&
  Nimages ();

  void
  Nimages (const Nimages_type& x);

  // Nslabs
  //
  typedef ::xml_schema::integer Nslabs_type;
  typedef ::xsd::cxx::tree::traits< Nslabs_type, char > Nslabs_traits;

  const Nslabs_type&
  Nslabs () const;

  Nslabs_type&
  Nslabs ();

  void
  Nslabs (const Nslabs_type& x);

  // Beta
  //
  typedef ::xml_schema::float_ Beta_type;
  typedef ::xsd::cxx::tree::traits< Beta_type, char > Beta_traits;

  const Beta_type&
  Beta () const;

  Beta_type&
  Beta ();

  void
  Beta (const Beta_type& x);

  // Constructors.
  //
  PowerGridConfig_t (const Nx_type&,
                     const Ny_type&,
                     const Nz_type&,
                     const Niter_type&,
                     const Ntimeseg_type&,
                     const Ncoils_type&,
                     const Nshots_type&,
                     const Nphases_type&,
                     const Nimages_type&,
                     const Nslabs_type&,
                     const Beta_type&);

  PowerGridConfig_t (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

  PowerGridConfig_t (const PowerGridConfig_t& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

  virtual PowerGridConfig_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  PowerGridConfig_t&
  operator= (const PowerGridConfig_t& x);

  virtual 
  ~PowerGridConfig_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< Nx_type > Nx_;
  ::xsd::cxx::tree::one< Ny_type > Ny_;
  ::xsd::cxx::tree::one< Nz_type > Nz_;
  ::xsd::cxx::tree::one< Niter_type > Niter_;
  ::xsd::cxx::tree::one< Ntimeseg_type > Ntimeseg_;
  ::xsd::cxx::tree::one< Ncoils_type > Ncoils_;
  ::xsd::cxx::tree::one< Nshots_type > Nshots_;
  ::xsd::cxx::tree::one< Nphases_type > Nphases_;
  ::xsd::cxx::tree::one< Nimages_type > Nimages_;
  ::xsd::cxx::tree::one< Nslabs_type > Nslabs_;
  ::xsd::cxx::tree::one< Beta_type > Beta_;
};

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

// Parse a URI or a local file.
//

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::std::string& uri,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::std::string& uri,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::std::string& uri,
                 ::xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse std::istream.
//

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 ::xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 const ::std::string& id,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 const ::std::string& id,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 const ::std::string& id,
                 ::xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse xercesc::InputSource.
//

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xercesc::InputSource& is,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xercesc::InputSource& is,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xercesc::InputSource& is,
                 ::xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse xercesc::DOMDocument.
//

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::xercesc::DOMDocument& d,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX__CONFIG_HXX
