// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "config.hxx"

// PowerGridConfig_t
// 

const PowerGridConfig_t::Nx_type& PowerGridConfig_t::
Nx () const
{
  return this->Nx_.get ();
}

PowerGridConfig_t::Nx_type& PowerGridConfig_t::
Nx ()
{
  return this->Nx_.get ();
}

void PowerGridConfig_t::
Nx (const Nx_type& x)
{
  this->Nx_.set (x);
}

const PowerGridConfig_t::Ny_type& PowerGridConfig_t::
Ny () const
{
  return this->Ny_.get ();
}

PowerGridConfig_t::Ny_type& PowerGridConfig_t::
Ny ()
{
  return this->Ny_.get ();
}

void PowerGridConfig_t::
Ny (const Ny_type& x)
{
  this->Ny_.set (x);
}

const PowerGridConfig_t::Nz_type& PowerGridConfig_t::
Nz () const
{
  return this->Nz_.get ();
}

PowerGridConfig_t::Nz_type& PowerGridConfig_t::
Nz ()
{
  return this->Nz_.get ();
}

void PowerGridConfig_t::
Nz (const Nz_type& x)
{
  this->Nz_.set (x);
}

const PowerGridConfig_t::Niter_type& PowerGridConfig_t::
Niter () const
{
  return this->Niter_.get ();
}

PowerGridConfig_t::Niter_type& PowerGridConfig_t::
Niter ()
{
  return this->Niter_.get ();
}

void PowerGridConfig_t::
Niter (const Niter_type& x)
{
  this->Niter_.set (x);
}

const PowerGridConfig_t::Ntimeseg_type& PowerGridConfig_t::
Ntimeseg () const
{
  return this->Ntimeseg_.get ();
}

PowerGridConfig_t::Ntimeseg_type& PowerGridConfig_t::
Ntimeseg ()
{
  return this->Ntimeseg_.get ();
}

void PowerGridConfig_t::
Ntimeseg (const Ntimeseg_type& x)
{
  this->Ntimeseg_.set (x);
}

const PowerGridConfig_t::Ncoils_type& PowerGridConfig_t::
Ncoils () const
{
  return this->Ncoils_.get ();
}

PowerGridConfig_t::Ncoils_type& PowerGridConfig_t::
Ncoils ()
{
  return this->Ncoils_.get ();
}

void PowerGridConfig_t::
Ncoils (const Ncoils_type& x)
{
  this->Ncoils_.set (x);
}

const PowerGridConfig_t::Nshots_type& PowerGridConfig_t::
Nshots () const
{
  return this->Nshots_.get ();
}

PowerGridConfig_t::Nshots_type& PowerGridConfig_t::
Nshots ()
{
  return this->Nshots_.get ();
}

void PowerGridConfig_t::
Nshots (const Nshots_type& x)
{
  this->Nshots_.set (x);
}

const PowerGridConfig_t::Nphases_type& PowerGridConfig_t::
Nphases () const
{
  return this->Nphases_.get ();
}

PowerGridConfig_t::Nphases_type& PowerGridConfig_t::
Nphases ()
{
  return this->Nphases_.get ();
}

void PowerGridConfig_t::
Nphases (const Nphases_type& x)
{
  this->Nphases_.set (x);
}

const PowerGridConfig_t::Nimages_type& PowerGridConfig_t::
Nimages () const
{
  return this->Nimages_.get ();
}

PowerGridConfig_t::Nimages_type& PowerGridConfig_t::
Nimages ()
{
  return this->Nimages_.get ();
}

void PowerGridConfig_t::
Nimages (const Nimages_type& x)
{
  this->Nimages_.set (x);
}

const PowerGridConfig_t::Nslabs_type& PowerGridConfig_t::
Nslabs () const
{
  return this->Nslabs_.get ();
}

PowerGridConfig_t::Nslabs_type& PowerGridConfig_t::
Nslabs ()
{
  return this->Nslabs_.get ();
}

void PowerGridConfig_t::
Nslabs (const Nslabs_type& x)
{
  this->Nslabs_.set (x);
}

const PowerGridConfig_t::Beta_type& PowerGridConfig_t::
Beta () const
{
  return this->Beta_.get ();
}

PowerGridConfig_t::Beta_type& PowerGridConfig_t::
Beta ()
{
  return this->Beta_.get ();
}

void PowerGridConfig_t::
Beta (const Beta_type& x)
{
  this->Beta_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// PowerGridConfig_t
//

PowerGridConfig_t::
PowerGridConfig_t (const Nx_type& Nx,
                   const Ny_type& Ny,
                   const Nz_type& Nz,
                   const Niter_type& Niter,
                   const Ntimeseg_type& Ntimeseg,
                   const Ncoils_type& Ncoils,
                   const Nshots_type& Nshots,
                   const Nphases_type& Nphases,
                   const Nimages_type& Nimages,
                   const Nslabs_type& Nslabs,
                   const Beta_type& Beta)
: ::xml_schema::type (),
  Nx_ (Nx, this),
  Ny_ (Ny, this),
  Nz_ (Nz, this),
  Niter_ (Niter, this),
  Ntimeseg_ (Ntimeseg, this),
  Ncoils_ (Ncoils, this),
  Nshots_ (Nshots, this),
  Nphases_ (Nphases, this),
  Nimages_ (Nimages, this),
  Nslabs_ (Nslabs, this),
  Beta_ (Beta, this)
{
}

PowerGridConfig_t::
PowerGridConfig_t (const PowerGridConfig_t& x,
                   ::xml_schema::flags f,
                   ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  Nx_ (x.Nx_, f, this),
  Ny_ (x.Ny_, f, this),
  Nz_ (x.Nz_, f, this),
  Niter_ (x.Niter_, f, this),
  Ntimeseg_ (x.Ntimeseg_, f, this),
  Ncoils_ (x.Ncoils_, f, this),
  Nshots_ (x.Nshots_, f, this),
  Nphases_ (x.Nphases_, f, this),
  Nimages_ (x.Nimages_, f, this),
  Nslabs_ (x.Nslabs_, f, this),
  Beta_ (x.Beta_, f, this)
{
}

PowerGridConfig_t::
PowerGridConfig_t (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f,
                   ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  Nx_ (this),
  Ny_ (this),
  Nz_ (this),
  Niter_ (this),
  Ntimeseg_ (this),
  Ncoils_ (this),
  Nshots_ (this),
  Nphases_ (this),
  Nimages_ (this),
  Nslabs_ (this),
  Beta_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void PowerGridConfig_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Nx
    //
    if (n.name () == "Nx" && n.namespace_ ().empty ())
    {
      if (!Nx_.present ())
      {
        this->Nx_.set (Nx_traits::create (i, f, this));
        continue;
      }
    }

    // Ny
    //
    if (n.name () == "Ny" && n.namespace_ ().empty ())
    {
      if (!Ny_.present ())
      {
        this->Ny_.set (Ny_traits::create (i, f, this));
        continue;
      }
    }

    // Nz
    //
    if (n.name () == "Nz" && n.namespace_ ().empty ())
    {
      if (!Nz_.present ())
      {
        this->Nz_.set (Nz_traits::create (i, f, this));
        continue;
      }
    }

    // Niter
    //
    if (n.name () == "Niter" && n.namespace_ ().empty ())
    {
      if (!Niter_.present ())
      {
        this->Niter_.set (Niter_traits::create (i, f, this));
        continue;
      }
    }

    // Ntimeseg
    //
    if (n.name () == "Ntimeseg" && n.namespace_ ().empty ())
    {
      if (!Ntimeseg_.present ())
      {
        this->Ntimeseg_.set (Ntimeseg_traits::create (i, f, this));
        continue;
      }
    }

    // Ncoils
    //
    if (n.name () == "Ncoils" && n.namespace_ ().empty ())
    {
      if (!Ncoils_.present ())
      {
        this->Ncoils_.set (Ncoils_traits::create (i, f, this));
        continue;
      }
    }

    // Nshots
    //
    if (n.name () == "Nshots" && n.namespace_ ().empty ())
    {
      if (!Nshots_.present ())
      {
        this->Nshots_.set (Nshots_traits::create (i, f, this));
        continue;
      }
    }

    // Nphases
    //
    if (n.name () == "Nphases" && n.namespace_ ().empty ())
    {
      if (!Nphases_.present ())
      {
        this->Nphases_.set (Nphases_traits::create (i, f, this));
        continue;
      }
    }

    // Nimages
    //
    if (n.name () == "Nimages" && n.namespace_ ().empty ())
    {
      if (!Nimages_.present ())
      {
        this->Nimages_.set (Nimages_traits::create (i, f, this));
        continue;
      }
    }

    // Nslabs
    //
    if (n.name () == "Nslabs" && n.namespace_ ().empty ())
    {
      if (!Nslabs_.present ())
      {
        this->Nslabs_.set (Nslabs_traits::create (i, f, this));
        continue;
      }
    }

    // Beta
    //
    if (n.name () == "Beta" && n.namespace_ ().empty ())
    {
      if (!Beta_.present ())
      {
        this->Beta_.set (Beta_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!Nx_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Nx",
      "");
  }

  if (!Ny_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Ny",
      "");
  }

  if (!Nz_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Nz",
      "");
  }

  if (!Niter_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Niter",
      "");
  }

  if (!Ntimeseg_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Ntimeseg",
      "");
  }

  if (!Ncoils_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Ncoils",
      "");
  }

  if (!Nshots_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Nshots",
      "");
  }

  if (!Nphases_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Nphases",
      "");
  }

  if (!Nimages_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Nimages",
      "");
  }

  if (!Nslabs_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Nslabs",
      "");
  }

  if (!Beta_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Beta",
      "");
  }
}

PowerGridConfig_t* PowerGridConfig_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class PowerGridConfig_t (*this, f, c);
}

PowerGridConfig_t& PowerGridConfig_t::
operator= (const PowerGridConfig_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->Nx_ = x.Nx_;
    this->Ny_ = x.Ny_;
    this->Nz_ = x.Nz_;
    this->Niter_ = x.Niter_;
    this->Ntimeseg_ = x.Ntimeseg_;
    this->Ncoils_ = x.Ncoils_;
    this->Nshots_ = x.Nshots_;
    this->Nphases_ = x.Nphases_;
    this->Nimages_ = x.Nimages_;
    this->Nslabs_ = x.Nslabs_;
    this->Beta_ = x.Beta_;
  }

  return *this;
}

PowerGridConfig_t::
~PowerGridConfig_t ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::std::string& u,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::auto_ptr< ::PowerGridConfig_t > (
    ::PowerGridConfig (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::std::string& u,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::PowerGridConfig_t > (
    ::PowerGridConfig (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::PowerGridConfig_t > (
    ::PowerGridConfig (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::PowerGridConfig (isrc, f, p);
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::PowerGridConfig (isrc, h, f, p);
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::PowerGridConfig (isrc, h, f, p);
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::PowerGridConfig (isrc, f, p);
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::PowerGridConfig (isrc, h, f, p);
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::PowerGridConfig (isrc, h, f, p);
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xercesc::InputSource& i,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::auto_ptr< ::PowerGridConfig_t > (
    ::PowerGridConfig (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xercesc::InputSource& i,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::PowerGridConfig_t > (
    ::PowerGridConfig (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::PowerGridConfig_t > (
    ::PowerGridConfig (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (const ::xercesc::DOMDocument& doc,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::auto_ptr< ::PowerGridConfig_t > (
      ::PowerGridConfig (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "PowerGridConfig" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::PowerGridConfig_t > r (
      ::xsd::cxx::tree::traits< ::PowerGridConfig_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "PowerGridConfig",
    "");
}

::std::auto_ptr< ::PowerGridConfig_t >
PowerGridConfig (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "PowerGridConfig" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::PowerGridConfig_t > r (
      ::xsd::cxx::tree::traits< ::PowerGridConfig_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "PowerGridConfig",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

